
version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    #restart: always
    # ports:
    #   - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    network_mode: host
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    network_mode: host
    #restart: always
    # ports:
    #   - "8086:8086"
    environment:
      - INFLUXDB_DB=telemetry
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    network_mode: host
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    network_mode: host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - ./alert_json.txt:/var/log/snort/alert_json.txt
    depends_on:
      - influxdb

# Snort service runs on the host
